language: cpp
os:
    - linux
    - osx

notifications:
    email: true

before_install:
    - if [ `uname` = "Linux" ]; then
        sudo apt-get update -qq -y;
        sudo apt-get install libsnappy-dev libev-dev libgmp-dev cpanminus perl -y;
        sudo cpanm --quiet --notest --skip-satisfied --force Redis;
      elif [ `uname` = "Darwin" ]; then
        brew update;
        brew install snappy;
        brew install libev;
        brew install gmp;
        brew install cpanminus;
        sudo cpanm --quiet --notest --skip-satisfied --force Redis;
      fi

script:
    - make 
    - make test
    - echo "Ready for packaging..."
