language: cpp
os:
    - linux
    - osx

notifications:
    email: true

before_install:
    - if [ `uname` = "Linux" ]; then
        sudo apt-get update -qq -y;
        sudo apt-get install libredis-perl libsnappy-dev libev-dev libgmp-dev -y;
      elif [ `uname` = "Darwin" ]; then
        brew update;
        brew install snappy;
        brew install libev;
        brew install gmp;
        cpan install Redis;
      fi

script:
    - make 
    - make test
    - echo "Ready for packaging..."
